# Generated by Django 5.2.10 on 2026-01-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='mkv2cast', max_length=100)),
                ('site_tagline', models.CharField(blank=True, default='Convert videos for Chromecast', max_length=200)),
                ('logo_url', models.URLField(blank=True)),
                ('logo_file', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('favicon_file', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('primary_color', models.CharField(default='#6366f1', max_length=7)),
                ('secondary_color', models.CharField(default='#8b5cf6', max_length=7)),
                ('default_container', models.CharField(choices=[('mkv', 'MKV'), ('mp4', 'MP4')], default='mkv', max_length=10)),
                ('default_hw_backend', models.CharField(choices=[('auto', 'Auto'), ('vaapi', 'VAAPI'), ('qsv', 'QSV'), ('cpu', 'CPU')], default='auto', max_length=10)),
                ('default_quality_preset', models.CharField(choices=[('fast', 'Fast'), ('balanced', 'Balanced'), ('quality', 'High Quality')], default='balanced', max_length=20)),
                ('max_file_size', models.BigIntegerField(default=10737418240)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True, default='The service is currently under maintenance. Please try again later.')),
                ('allow_registration', models.BooleanField(default=True)),
                ('require_email_verification', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
                'db_table': 'accounts_site_settings',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('local', 'Local'), ('google', 'Google'), ('github', 'GitHub')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='backup_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
    ]
