# Generated by Django 5.2.10 on 2026-01-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionjob',
            name='audio_lang',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='audio_track',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='no_silence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='no_subtitles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='nvenc_cq',
            field=models.IntegerField(default=23),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='prefer_forced_subs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='skip_when_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='subtitle_lang',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='subtitle_track',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversionjob',
            name='hw_backend',
            field=models.CharField(choices=[('auto', 'Auto'), ('nvenc', 'NVENC'), ('vaapi', 'VAAPI'), ('qsv', 'QSV'), ('cpu', 'CPU')], default='auto', max_length=10),
        ),
    ]
