# Generated by Django 5.2.10 on 2026-01-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0002_add_new_mkv2cast_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionjob',
            name='amf_quality',
            field=models.IntegerField(default=23),
        ),
        migrations.AlterField(
            model_name='conversionjob',
            name='hw_backend',
            field=models.CharField(
                choices=[
                    ('auto', 'Auto'),
                    ('nvenc', 'NVENC'),
                    ('amf', 'AMD AMF'),
                    ('vaapi', 'VAAPI'),
                    ('qsv', 'QSV'),
                    ('cpu', 'CPU'),
                ],
                default='auto',
                max_length=10
            ),
        ),
    ]
